In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf

In [2]:
# Read in csv file
file_path = pd.read_csv(f"/content/drive/MyDrive/Colab Notebooks/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")
#file_path = pd.read_csv(f"/content/drive/MyDrive/Colab Notebooks/diabetes_binary_health_indicators_BRFSS2015.csv")
file_path

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
# Convert csv to dataframe
diabetes_df = pd.DataFrame(file_path)
diabetes_df

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [4]:
# List columns for review
diabetes_df.columns.to_list()

['Diabetes_binary',
 'HighBP',
 'HighChol',
 'CholCheck',
 'BMI',
 'Smoker',
 'Stroke',
 'HeartDiseaseorAttack',
 'PhysActivity',
 'Fruits',
 'Veggies',
 'HvyAlcoholConsump',
 'AnyHealthcare',
 'NoDocbcCost',
 'GenHlth',
 'MentHlth',
 'PhysHlth',
 'DiffWalk',
 'Sex',
 'Age',
 'Education',
 'Income']

In [5]:
# Drop unnecessary columns
diabetes_df_drop = diabetes_df.drop(columns=['NoDocbcCost', 'GenHlth', 'MentHlth', 'PhysHlth', 'DiffWalk'])
diabetes_df_drop

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,9.0,6.0,2.0

In [6]:
# Filter through df to pull needed columns and rename 'Diabetes_binary ' to 'Diabetes_status' to pull target variable and features
consumption_df = diabetes_df.filter(['Diabetes_binary', 'Smoker', 'HvyAlcoholConsump', 'Fruits', 'Veggies'], axis=1)
consumption_df.rename(columns={'Diabetes_binary': 'Diabetes_Status'}, inplace=True)
consumption_df

       Diabetes_Status  Smoker  HvyAlcoholConsump  Fruits  Veggies
0                  0.0     0.0                0.0     0.0      1.0
1                  0.0     1.0                0.0     1.0      0.0
2                  0.0     0.0                0.0     1.0      1.0
3                  0.0     1.0                0.0     1.0      1.0
4                  0.0     1.0                0.0     1.0      1.0
...                ...     ...                ...     ...      ...
70687              1.0     0.0                0.0     0.0      1.0
70688              1.0     1.0                0.0     1.0      1.0
70689              1.0     0.0                0.0     1.0      0.0
70690              1.0     0.0                0.0     0.0      0.0
70691              1.0     0.0                0.0     1.0      0.0

[70692 rows x 5 columns]

In [ ]:
# Convert new dataframe to csv file for future refernces
#consumption_df.to_csv("../Resources/consumption_df.csv")

In [7]:
# Check df and data types  
consumption_df.dtypes

Diabetes_Status      float64
Smoker               float64
HvyAlcoholConsump    float64
Fruits               float64
Veggies              float64
dtype: object

In [12]:
# Randomize dataset prior to training

consumption_df_random = consumption_df.sample(frac=1, random_state=1)

In [13]:
# Remove Diabetes_Status target from features data

y = consumption_df_random.Diabetes_Status.values
X = consumption_df_random.drop(columns="Diabetes_Status").values

In [14]:
# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    random_state=1,
                                                    stratify=y)

In [15]:
# Preprocess numerical data for neural network

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
# Define the deep learning model 
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=4))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=25)

# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/25
1657/1657 [==============================] - 5s 3ms/step - loss: 0.6822 - accuracy: 0.5622
Epoch 2/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6810 - accuracy: 0.5647
Epoch 3/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6809 - accuracy: 0.5652
Epoch 4/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6809 - accuracy: 0.5640
Epoch 5/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5652
Epoch 6/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5649
Epoch 7/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5642
Epoch 8/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5646
Epoch 9/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6808 - accuracy: 0.5637
Epoch 10/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5648
Epoch 11/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6806 - accuracy: 0.5645
Epoch 12/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5641
Epoch 13/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5653
Epoch 14/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5649
Epoch 15/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5647
Epoch 16/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5651
Epoch 17/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5650
Epoch 18/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5653
Epoch 19/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5652
Epoch 20/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6806 - accuracy: 0.5640
Epoch 21/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5646
Epoch 22/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6808 - accuracy: 0.5648
Epoch 23/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5646
Epoch 24/25
1657/1657 [==============================] - 4s 2ms/step - loss: 0.6807 - accuracy: 0.5642
Epoch 25/25
1657/1657 [==============================] - 3s 2ms/step - loss: 0.6807 - accuracy: 0.5652
553/553 - 1s - loss: 0.6805 - accuracy: 0.5626 - 649ms/epoch - 1ms/step
Loss: 0.6804748177528381, Accuracy: 0.5626096129417419